log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://root:root@localhost:5432/blobs?sslmode=disable"

listener:
  addr: :8000

jwt:
  secret_key: "7365637265742d6b6579"
  expiration_time: 24h

db_cleaner:
  period: 24h

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: verify-proxy
  service_port: 80
